# Generated by Django 4.2.9 on 2025-09-24 13:00

import apps.pages.utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("info", models.CharField(default="", max_length=100)),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=Decimal("0.0"),
                        max_digits=19,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=apps.pages.utils.localtime_now, verbose_name="Datetime"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Account", "Account"),
                        ],
                        default="Account",
                        max_length=16,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Expenses", "Expenses"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        default="Income",
                        max_length=16,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=256, verbose_name="Remarks"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
        ),
    ]
